# Generated by Django 6.0.7 on 2026-08-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=10),
        ),
    ]
